### ISSUE TITLE
Hacky workarounds for CORS in development

### ISSUE THREAD

**Issue by AlexLukasT** [DSMaVie/quems-frontend#6]
Problem: For testing purpose starting the frontend with `npm start` and running the API on `localhost:5000` leads to [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) errors when making requests.   
Using the temporary solution from [this](https://www.telerik.com/blogs/dealing-with-cors-in-create-react-app) article sets `"proxy": "localhost:5000"` in `package.json` to forward everything not on `/` to "localhost:5000".

Maybe there is a better solution?
When will the backend provide the frontend?

**Comment by DSMaVie** [comment]
not sure for now we should work with the work around. we should keep the repo open. At the end of dev this could be automatically mitigated when wrapping the back and frondend in separate containers.

**Comment by DSMaVie** [comment]
Dupicate of #13
